### ISSUE TITLE
IP-only authentication

### ISSUE THREAD

**Issue by pkong-ds** [oursky/pageship#27]
## Use Case

To authenticate a deployer access just by IP, no github user or github action

## Problem

Running `pageship deploy -y` on a valid IP still prompts Github Username input

```sh
$ pageship deploy --site main -y
✗ GitHub user name: █
```

### pageship.toml
```toml
[app]
id = "nba-result-prediction"

team = [
{ ipRange="94.190.220.240/32", access="deployer" }
]
...
```

## Investigation

- Seems every command runs [`ensureAuth`, which requires a token that can only be obtained by `githubOIDC` or `githubSSH`](https://github.com/oursky/pageship/blob/main/cmd/pageship/app/auth.go#L31-L36)
- [access-control.md](https://github.com/oursky/pageship/blob/39f642360e5a74ca016cf4e0ca373e5855caae52/docs/guides/features/access-control.md#ip-address) seems to suggest that IP-only authentication is available (or is it just an additional check on top of user auth token?)
